### ISSUE TITLE
Hole in Regione Marche (Pesaro Urbino) in regioni and province geo JSON

### ISSUE THREAD

**Issue by francescocretti** [openpolis/geojson-italy#16]
There's a strange hole in the middle of Marche in the province (Pesaro Urbino) and regioni (Marche) geo JSON

![Schermata del 2022-08-23 15-26-50](https://user-images.githubusercontent.com/11871906/186170745-3cdf8974-1994-47ba-937a-53e4b09ffebe.png)

**Comment by guglielmo** [comment]
The municipality of Pesaro added that territory (municipality of Monteciccardo and possibly others) as of june 2020. 
The geometry was not correctly modified in the source.

I am trying to adjust this data, before releasing an update for 2022.

**Comment by guglielmo** [comment]
In the current version the hole has been patched.
