### ISSUE TITLE
Error: [clean] Received one or more unexpected parameters: encoding=utf8

### ISSUE THREAD

**Issue by armandoschianodicola** [openpolis/geojson-italy#19]
Hello,

When launching any of the bash scripts commands `./generate_geojson.sh` or `./generate_topojson.sh` it returns me the following error:

`Error: [clean] Received one or more unexpected parameters: encoding=utf8
Run mapshaper -h to view help`

These are my settings:

OS: Ubuntu 22.04.4 LTS
Mapshaper version:  0.6.65
Node version: v18.13.0

**Comment by armandoschianodicola** [comment]
The problem seems to lie with the mapshaper version. At least in the 0.6.65 version (if not before) `encoding` is not an option of parameter -clean but of parameter -i

I have prepared a PR to fix this: https://github.com/openpolis/geojson-italy/pull/20 
I have also updated README to pinpoint the mapshaper version in use

**Comment by guglielmo** [comment]
Hi Armando, just merged your PR today. Thanks!
