### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by mlocati** [openpolis/geojson-italy#5]
What's the license for the data in the https://github.com/openpolis/geojson-italy repository?

**Comment by guglielmo** [comment]
Thank you for your question Michele, I completely overlooked this.
This is going to be addressed properly, and it will by CC-BY-4.0, https://creativecommons.org/licenses/by/4.0/.

The original data come from ISTAT, that licenses their data under CC-BY, as well.

**Comment by mlocati** [comment]
Thanks for the lightning fast reply!
