### ISSUE TITLE
Wrong values of com_istat_code in topojson/limits_IT_all.topo.json

### ISSUE THREAD

**Issue by mlocati** [openpolis/geojson-italy#6]
I've compared the values of the `com_istat_code` attributes of the municipalities found in the [`topojson/limits_IT_all.topo.json` file](https://github.com/openpolis/geojson-italy/blob/e89ef8c6194402f45539b3d7993d50fbe4a75e39/topojson/limits_IT_all.topo.json) with then [`Elenco-comuni-italiani.xls`](https://www.istat.it/storage/codici-unita-amministrative/Elenco-comuni-italiani.xls) file provided by ISTAT, and I found a few errors.
You can also see that those municipality codes are wrong because they don't start with the province codes (`prov_istat_code` attribute).

Here's the list (you can also [download this list in CSV format](https://github.com/openpolis/geojson-italy/files/6187920/wrong-com_istat_codes.txt) for your convenience):

| name | prov_istat_code | wrong com_istat_code | correct com_istat_code |
|---|:---:|:---:|:---:|
| Abbadia Lariana | 097 | 013001 | 097001 |
| Aggius | 090 | 104001 | 090001 |
| Aglientu | 090 | 104002 | 090062 |
| Agrate Brianza | 108 | 015003 | 108001 |
| Aicurzio | 108 | 015004 | 108002 |
| Albiate | 108 | 015006 | 108003 |
| Amandola | 109 | 044004 | 109002 |
| Andorno Micca | 096 | 002005 | 096002 |
| Annone di Brianza | 097 | 013008 | 097003 |
| Antrona Schieranco | 103 | 003003 | 103001 |
| Anzola d'Ossola | 103 | 003004 | 103002 |
| Arcore | 108 | 015008 | 108004 |
| Arena | 102 | 079006 | 102002 |
| Arola | 103 | 003007 | 103004 |
| Arzachena | 090 | 104004 | 090006 |
| Arzana | 091 | 105001 | 091002 |
| Ballabio | 097 | 013014 | 097004 |
| Bari Sardo | 091 | 105002 | 091005 |
| Barlassina | 108 | 015013 | 108005 |
| Barzago | 097 | 013016 | 097005 |
| Baunei | 091 | 105003 | 091006 |
| Bellaria-Igea Marina | 099 | 040002 | 099001 |
| Belmonte Piceno | 109 | 044008 | 109003 |
| Belvedere di Spinello | 101 | 079010 | 101001 |
| Benna | 096 | 002010 | 096003 |
| Biella | 096 | 002012 | 096004 |
| Bognanco | 103 | 003020 | 103012 |
| Borghetto Lodigiano | 098 | 015028 | 098004 |
| Borgo San Giovanni | 098 | 015029 | 098005 |
| Bortigiadas | 090 | 104007 | 090014 |
| Brembio | 098 | 015031 | 098006 |
| Briosco | 108 | 015033 | 108011 |
| Brivio | 097 | 013031 | 097010 |
| Brugherio | 108 | 015034 | 108012 |
| Buddusò | 090 | 104008 | 090017 |
| Buggerru | 111 | 107001 | 111006 |
| Bulciago | 097 | 013033 | 097011 |
| Burcei | 111 | 092008 | 111007 |
| Caccuri | 101 | 079015 | 101002 |
| Calangianus | 090 | 104010 | 090021 |
| Calasca-Castiglione | 103 | 003029 | 103014 |
| Callabiana | 096 | 002022 | 096008 |
| Camandona | 096 | 002023 | 096009 |
| Cambiasca | 103 | 003031 | 103015 |
| Camburzano | 096 | 002024 | 096010 |
| Camparada | 108 | 015045 | 108014 |
| Campofilone | 109 | 044009 | 109004 |
| Candelo | 096 | 002027 | 096012 |
| Cannobio | 103 | 003034 | 103017 |
| Capistrano | 102 | 079016 | 102005 |
| Caprezzo | 103 | 003035 | 103018 |
| Caprile | 096 | 002028 | 096013 |
| Cardedu | 091 | 105004 | 091103 |
| Carenno | 097 | 016054 | 097014 |
| Carfizzi | 101 | 079019 | 101003 |
| Carloforte | 111 | 092013 | 111010 |
| Carnate | 108 | 015049 | 108016 |
| Casabona | 101 | 079021 | 101004 |
| Casale Corte Cerro | 103 | 003038 | 103019 |
| Casalmaiocco | 098 | 015053 | 098009 |
| Casargo | 097 | 013049 | 097015 |
| Casatenovo | 097 | 013051 | 097016 |
| Caselle Landi | 098 | 015056 | 098011 |
| Caselle Lurani | 098 | 015057 | 098012 |
| Cassina Valsassina | 097 | 013056 | 097018 |
| Castello di Brianza | 097 | 013057 | 097019 |
| Castiraga Vidardo | 098 | 015065 | 098015 |
| Cattolica | 099 | 040006 | 099002 |
| Cavenago di Brianza | 108 | 015068 | 108017 |
| Ceriano Laghetto | 108 | 015069 | 108018 |
| Cernusco Lombardone | 097 | 013066 | 097020 |
| Cervignano d'Adda | 098 | 015073 | 098018 |
| Cesana Brianza | 097 | 013067 | 097021 |
| Cesano Maderno | 108 | 015075 | 108019 |
| Cesara | 103 | 003050 | 103022 |
| Cirò Marina | 101 | 079032 | 101008 |
| Civate | 097 | 013069 | 097022 |
| Cogliate | 108 | 015080 | 108020 |
| Colico | 097 | 013072 | 097023 |
| Collinas | 111 | 092014 | 111012 |
| Concorezzo | 108 | 015084 | 108021 |
| Cornegliano Laudense | 098 | 015089 | 098021 |
| Corno Giovine | 098 | 015090 | 098022 |
| Correzzana | 108 | 015092 | 108022 |
| Cossogno | 103 | 003053 | 103023 |
| Costa Masnaga | 097 | 013079 | 097026 |
| Cotronei | 101 | 079035 | 101009 |
| Craveggia | 103 | 003054 | 103024 |
| Cremeno | 097 | 013082 | 097029 |
| Crodo | 103 | 003057 | 103026 |
| Crucoli | 101 | 079038 | 101011 |
| Cutro | 101 | 079040 | 101012 |
| Dervio | 097 | 013086 | 097030 |
| Dolianova | 111 | 092017 | 111014 |
| Domusnovas | 111 | 092019 | 111016 |
| Donori | 111 | 092020 | 111017 |
| Dorzano | 096 | 002056 | 096025 |
| Drapia | 102 | 079045 | 102009 |
| Erve | 097 | 016095 | 097034 |
| Escalaplano | 111 | 092110 | 111018 |
| Esino Lario | 097 | 013096 | 097035 |
| Esterzili | 111 | 091022 | 111020 |
| Fabrizia | 102 | 079046 | 102010 |
| Filadelfia | 102 | 079049 | 102011 |
| Flussio | 095 | 091023 | 095080 |
| Fombio | 098 | 015102 | 098026 |
| Formazza | 103 | 003067 | 103031 |
| Francavilla Angitola | 102 | 079053 | 102014 |
| Gaglianico | 096 | 002060 | 096026 |
| Gairo | 091 | 105006 | 091026 |
| Galgagnano | 098 | 015104 | 098027 |
| Garbagnate Monastero | 097 | 013104 | 097037 |
| Garlate | 097 | 013105 | 097038 |
| Genoni | 111 | 095081 | 111023 |
| Genuri | 111 | 106005 | 111024 |
| Germagno | 103 | 003072 | 103032 |
| Gesturi | 111 | 092025 | 111027 |
| Giba | 111 | 092026 | 111028 |
| Gifflenga | 096 | 002063 | 096027 |
| Giussano | 108 | 015107 | 108024 |
| Golfo Aranci | 090 | 104011 | 090083 |
| Goni | 111 | 092027 | 111029 |
| Guamaggiore | 111 | 092030 | 111032 |
| Gurro | 103 | 003080 | 103036 |
| Guspini | 111 | 106008 | 111034 |
| Ilbono | 091 | 105008 | 091032 |
| Imbersago | 097 | 013115 | 097039 |
| Isili | 111 | 091034 | 111036 |
| Isola di Capo Rizzuto | 101 | 079064 | 101013 |
| La Maddalena | 090 | 104012 | 090035 |
| Las Plassas | 111 | 106009 | 111037 |
| Lazzate | 108 | 015117 | 108025 |
| Lesmo | 108 | 015120 | 108026 |
| Limbadi | 102 | 079067 | 102019 |
| Loiri Porto San Paolo | 090 | 104013 | 090084 |
| Lomagna | 097 | 013132 | 097044 |
| Lunamatrona | 111 | 092035 | 111038 |
| Macherio | 108 | 015129 | 108029 |
| Macugnaga | 103 | 003086 | 103039 |
| Madonna del Sasso | 103 | 003087 | 103040 |
| Magliano di Tenna | 109 | 044026 | 109010 |
| Magnano | 096 | 002073 | 096030 |
| Magomadas | 095 | 091045 | 095083 |
| Maierato | 102 | 079070 | 102020 |
| Mairago | 098 | 015132 | 098034 |
| Malesco | 103 | 003089 | 103041 |
| Malgrate | 097 | 013140 | 097045 |
| Mandas | 111 | 092036 | 111039 |
| Margno | 097 | 013142 | 097047 |
| Marudo | 098 | 015135 | 098036 |
| Massalengo | 098 | 015137 | 098037 |
| Massazza | 096 | 002074 | 096031 |
| Meleti | 098 | 015141 | 098038 |
| Melissa | 101 | 079075 | 101014 |
| Mesoraca | 101 | 079076 | 101015 |
| Mezzago | 108 | 015145 | 108031 |
| Mezzana Mortigliengo | 096 | 002076 | 096033 |
| Miazzina | 103 | 003099 | 103045 |
| Misinto | 108 | 015147 | 108032 |
| Modolo | 095 | 091048 | 095084 |
| Moggio | 097 | 013150 | 097050 |
| Mondaino | 099 | 040023 | 099006 |
| Mongiana | 102 | 079079 | 102022 |
| Mongrando | 096 | 002080 | 096035 |
| Montanaso Lombardo | 098 | 015148 | 098040 |
| Monte Marenzo | 097 | 016138 | 097052 |
| Monte Vidon Corrado | 109 | 044051 | 109026 |
| Montecrestese | 103 | 003101 | 103046 |
| Montefortino | 109 | 044037 | 109015 |
| Montegridolfo | 099 | 040026 | 099009 |
| Monterubbiano | 109 | 044047 | 109022 |
| Montevecchia | 097 | 013247 | 097053 |
| Monticello Brianza | 097 | 013156 | 097054 |
| Montottone | 109 | 044052 | 109027 |
| Morciano di Romagna | 099 | 040029 | 099011 |
| Moresco | 109 | 044053 | 109028 |
| Morterone | 097 | 013158 | 097055 |
| Mottalciata | 096 | 002083 | 096037 |
| Musei | 111 | 107011 | 111043 |
| Muzzano | 096 | 002084 | 096038 |
| Narcao | 111 | 092041 | 111044 |
| Netro | 096 | 002085 | 096039 |
| Nonio | 103 | 003105 | 103048 |
| Nova Milanese | 108 | 015156 | 108035 |
| Nuragus | 111 | 091052 | 111045 |
| Nuraminis | 111 | 092042 | 111047 |
| Nurri | 111 | 091054 | 111048 |
| Nuxis | 111 | 092043 | 111049 |
| Occhieppo Superiore | 096 | 002087 | 096041 |
| Oggebbio | 103 | 003107 | 103049 |
| Olgiate Molgora | 097 | 013166 | 097058 |
| Ornavasso | 103 | 003111 | 103051 |
| Ortacesus | 111 | 092044 | 111051 |
| Ortezzano | 109 | 044055 | 109029 |
| Osnago | 097 | 013171 | 097061 |
| Ospedaletto Lodigiano | 098 | 015162 | 098043 |
| Ossago Lodigiano | 098 | 015163 | 098044 |
| Pabillonis | 111 | 106011 | 111052 |
| Palau | 090 | 104020 | 090054 |
| Parghelia | 102 | 079091 | 102026 |
| Pauli Arbarei | 111 | 092046 | 111053 |
| Pedaso | 109 | 044057 | 109030 |
| Perdasdefogu | 091 | 105014 | 091072 |
| Perdaxius | 111 | 107014 | 111054 |
| Perledo | 097 | 013181 | 097067 |
| Pescate | 097 | 013182 | 097068 |
| Pettinengo | 096 | 002092 | 096042 |
| Piatto | 096 | 002094 | 096043 |
| Piedimulera | 103 | 003117 | 103053 |
| Pieve Fissiraga | 098 | 015174 | 098045 |
| Pieve Vergonte | 103 | 003118 | 103054 |
| Piscinas | 111 | 107015 | 111056 |
| Pizzoni | 102 | 079098 | 102028 |
| Poggio a Caiano | 100 | 048051 | 100004 |
| Ponderano | 096 | 002100 | 096047 |
| Ponzano di Fermo | 109 | 044059 | 109032 |
| Porto Sant'Elpidio | 109 | 044061 | 109034 |
| Premana | 097 | 013190 | 097069 |
| Premeno | 103 | 003123 | 103055 |
| Premia | 103 | 003124 | 103056 |
| Quarna Sopra | 103 | 003126 | 103058 |
| Quarna Sotto | 103 | 003127 | 103059 |
| Rapagnano | 109 | 044062 | 109035 |
| Re | 103 | 003128 | 103060 |
| Renate | 108 | 015180 | 108037 |
| Riccione | 099 | 040034 | 099013 |
| Robbiate | 097 | 013196 | 097071 |
| Rocca di Neto | 101 | 079103 | 101019 |
| Roccabernarda | 101 | 079102 | 101018 |
| Rogeno | 097 | 013198 | 097072 |
| Roncello | 108 | 015186 | 108055 |
| Ronco Biellese | 096 | 002117 | 096053 |
| Ronco Briantino | 108 | 015187 | 108038 |
| Roppolo | 096 | 002119 | 096054 |
| Sadali | 111 | 092119 | 111058 |
| Sagliano Micca | 096 | 002124 | 096056 |
| Salerano sul Lambro | 098 | 015190 | 098046 |
| Saludecio | 099 | 040038 | 099015 |
| Samatzai | 111 | 092053 | 111060 |
| San Bernardino Verbano | 103 | 003132 | 103061 |
| San Calogero | 102 | 079106 | 102032 |
| San Costantino Calabro | 102 | 079107 | 102033 |
| San Ferdinando di Puglia | 110 | 071045 | 110007 |
| San Fiorano | 098 | 015193 | 098047 |
| San Gavino Monreale | 111 | 106014 | 111062 |
| San Gregorio d'Ippona | 102 | 079109 | 102034 |
| San Leo | 099 | 041053 | 099025 |
| San Mauro Marchesato | 101 | 079111 | 101020 |
| San Nicolò Gerrei | 111 | 092058 | 111064 |
| San Nicola da Crissa | 102 | 079112 | 102035 |
| San Nicola dell'Alto | 101 | 079113 | 101021 |
| San Sperate | 111 | 092059 | 111065 |
| San Teodoro | 090 | 091076 | 090092 |
| San Vito | 111 | 092064 | 111066 |
| Sandigliano | 096 | 002130 | 096059 |
| Sanluri | 111 | 092057 | 111067 |
| Sant'Agata Feltria | 099 | 041055 | 099026 |
| Sant'Andrea Frius | 111 | 092061 | 111069 |
| Sant'Anna Arresi | 111 | 092062 | 111070 |
| Sant'Antioco | 111 | 092063 | 111071 |
| Sant'Antonio di Gallura | 090 | 104021 | 090085 |
| Sant'Elpidio a Mare | 109 | 044068 | 109037 |
| Sant'Onofrio | 102 | 079121 | 102036 |
| Santa Maria Hoè | 097 | 013209 | 097074 |
| Santa Teresa Gallura | 090 | 104022 | 090063 |
| Santa Vittoria in Matenano | 109 | 044067 | 109036 |
| Santarcangelo di Romagna | 099 | 040042 | 099018 |
| Santo Stefano Lodigiano | 098 | 015199 | 098051 |
| Sardara | 111 | 092065 | 111072 |
| Secugnago | 098 | 015203 | 098052 |
| Seregno | 108 | 015208 | 108039 |
| Serra San Bruno | 102 | 079128 | 102037 |
| Serramanna | 111 | 092072 | 111077 |
| Serri | 111 | 091080 | 111079 |
| Servigliano | 109 | 044069 | 109038 |
| Setzu | 111 | 092076 | 111080 |
| Seulo | 111 | 091082 | 111082 |
| Seveso | 108 | 015212 | 108040 |
| Siddi | 111 | 106021 | 111083 |
| Siliqua | 111 | 092078 | 111084 |
| Sirone | 097 | 013213 | 097075 |
| Siurgus Donigala | 111 | 092081 | 111086 |
| Smerillo | 109 | 044070 | 109039 |
| Soleminis | 111 | 092082 | 111087 |
| Somaglia | 098 | 015214 | 098054 |
| Sordevolo | 096 | 002139 | 096063 |
| Sordio | 098 | 015215 | 098055 |
| Sorianello | 102 | 079135 | 102039 |
| Sostegno | 096 | 002140 | 096064 |
| Spilinga | 102 | 079141 | 102042 |
| Stresa | 103 | 003142 | 103064 |
| Suello | 097 | 013220 | 097078 |
| Taceno | 097 | 013221 | 097079 |
| Talamello | 099 | 041063 | 099027 |
| Tavigliano | 096 | 002143 | 096066 |
| Telti | 090 | 104024 | 090080 |
| Tertenia | 091 | 105017 | 091089 |
| Teulada | 111 | 092084 | 111089 |
| Tinnura | 095 | 091092 | 095088 |
| Torre de' Busi | 016 | 097080 | 016215 |
| Torre San Patrizio | 109 | 044072 | 109040 |
| Tortolì | 091 | 105018 | 091095 |
| Trani | 110 | 072045 | 110009 |
| Trarego Viggiona | 103 | 003147 | 103066 |
| Tratalias | 111 | 107021 | 111090 |
| Trinitapoli | 110 | 071057 | 110010 |
| Turano Lodigiano | 098 | 015225 | 098058 |
| Valdengo | 096 | 002151 | 096071 |
| Valera Fratta | 098 | 015228 | 098059 |
| Vallanzengo | 096 | 002153 | 096072 |
| Valle San Nicolao | 096 | 002155 | 096074 |
| Vanzone con San Carlo | 103 | 003152 | 103070 |
| Varedo | 108 | 015231 | 108045 |
| Varzo | 103 | 003155 | 103071 |
| Veduggio con Colzano | 108 | 015233 | 108047 |
| Veglio | 096 | 002157 | 096075 |
| Verano Brianza | 108 | 015234 | 108048 |
| Vercurago | 097 | 016231 | 097086 |
| Verucchio | 099 | 040051 | 099020 |
| Vigliano Biellese | 096 | 002160 | 096077 |
| Villa del Bosco | 096 | 002161 | 096078 |
| Villacidro | 111 | 106025 | 111096 |
| Villadossola | 103 | 003162 | 103075 |
| Villagrande Strisaili | 091 | 105023 | 091101 |
| Villamar | 111 | 092093 | 111097 |
| Villamassargia | 111 | 107022 | 111098 |
| Villanova Tulo | 111 | 092122 | 111099 |
| Villanovaforru | 111 | 092095 | 111100 |
| Villanovafranca | 111 | 092096 | 111101 |
| Villaputzu | 111 | 092097 | 111103 |
| Villasalto | 111 | 092098 | 111104 |
| Villasanta | 108 | 015239 | 108049 |
| Villasor | 111 | 092101 | 111106 |
| Villaspeciosa | 111 | 092102 | 111107 |
| Villette | 103 | 003163 | 103076 |
| Vimercate | 108 | 015241 | 108050 |
| Zelo Buon Persico | 098 | 015245 | 098061 |
| Zimone | 096 | 002167 | 096081 |
| Zumaglia | 096 | 002169 | 096083 |

**Comment by guglielmo** [comment]
Great catch! The process generating the original `comuni.geojson` file was mixing up past and current identifiers. 
It now only takes into consideration current ones.

I've re-generated the files, and the issue can be considered closed with cca45f80e10d21ecb7a26eb7d550f1bc1f6003d8.
